version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: carbone_fazendas
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: carbone_fazendas_webserver
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8000:80"
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: carbone_fazendas_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: carbone_fazendas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
